config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  get "users" => redirect("/users/sign_up")

  get "books/search_by_title_author", to: "books#search", as: "search_books" # 検索フォーム表示 (indexアクション)
  post "books/search_by_title_author", to: "books#search_by_title_author", as: "books_search_by_title_author"
  get "books/:isbn", to: "books#show", as: "book"

  get "regions", to: "regions#index", as: "regions"
  get "regions/:pref_name", to: "regions#show", as: "region"
  get "/libraries/autocomplete", to: "libraries#autocomplete"

  get "libraries", to: "libraries#index", as: "library_index"
  get "library_detail", to: "libraries#show", as: "library_detail"

  resources :library_settings, only: [ :index, :create, :destroy ] do
  end


  get 'libraries/nearby', to: 'libraries#nearby'


  resources :want_to_read_books, only: [:index, :create, :destroy], param: :isbn
  resources :already_read_books, only: [:index, :create, :destroy], param: :isbn
end

app/models/already_read_book.rb
class AlreadyReadBook < ApplicationRecord
  belongs_to :user
end

app/controllers/already_read_books_controller.rb
class AlreadyReadBooksController < ApplicationController
  before_action :authenticate_user! # ログインユーザーのみアクセス可能にする
  before_action :set_book, only: [:create, :destroy]

  def index
    @already_read_books = current_user.already_read_books
  end

  def create
    @already_read_book = current_user.already_read_books.build(isbn: @isbn)

    respond_to do |format|
      if @already_read_book.save
        format.turbo_stream { render turbo_stream: turbo_stream.replace("already_read_#{@isbn}", partial: 'already_read_books/button', locals: { isbn: @isbn }) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.append("flash", partial: "shared/error_messages", locals: { message: "登録に失敗しました" }) }
      end
    end
  end

  def destroy
    @already_read_book = current_user.already_read_books.find_by(isbn: @isbn)
    
    if @already_read_book
      @already_read_book.destroy
      
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.remove("already_read_#{@isbn}"),
            turbo_stream.append("flash", partial: "shared/error_messages", locals: { message: "削除に成功しました" })
          ]
        end
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.append("flash", partial: "shared/error_messages", locals: { message: "削除に失敗しました" }) }
      end
    end
  end

  private

  def set_book
    @isbn = params[:isbn]
  end
end

app/helpers/already_read_books_helper.rb
module AlreadyReadBooksHelper
end

app/views/already_read_books/_button.html.erb
<% if current_user.already_read_books.exists?(isbn: isbn) %>
  <%= button_to already_read_book_path(isbn), method: :delete, remote: true, class: "bg-red-500 text-white px-4 py-2 rounded hover:bg-red-700", data: { isbn: isbn } do %>
    読んだ本を解除
  <% end %>
<% else %>
  <%= button_to already_read_books_path(isbn: isbn), method: :post, remote: true, class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700", data: { isbn: isbn } do %>
    読んだ本
  <% end %>
<% end %>

app/views/already_read_books/create.html.erb
<h1>AlreadyReadBooks#create</h1>
<p>Find me in app/views/already_read_books/create.html.erb</p>

app/views/already_read_books/destroy.html.erb
<h1>AlreadyReadBooks#destroy</h1>
<p>Find me in app/views/already_read_books/destroy.html.erb</p>

app/views/already_read_books/index.html.erb
<div class="container mx-auto p-4">
  <h1 class="text-2xl font-bold mb-4">読んだ本</h1>

  <% if @already_read_books.any? %>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <% @already_read_books.each do |book| %>
        <div class="border rounded-lg p-4">
          <p>ISBN: <%= book.isbn %></p>
          <%= button_to already_read_book_path(book.isbn), method: :delete, class: "bg-red-500 text-white px-4 py-2 rounded hover:bg-red-700" do %>
            読んだ本を解除
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>読んだ本はまだありません。</p>
  <% end %>
</div>