config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  get "users" => redirect("/users/sign_up")

  get "books/search_by_title_author", to: "books#search", as: "search_books" # 検索フォーム表示 (indexアクション)
  post "books/search_by_title_author", to: "books#search_by_title_author", as: "books_search_by_title_author"
  get "books/:isbn", to: "books#show", as: "book"

  get "regions", to: "regions#index", as: "regions"
  get "regions/:pref_name", to: "regions#show", as: "region"
  get "/libraries/autocomplete", to: "libraries#autocomplete"

  get "libraries", to: "libraries#index", as: "library_index"
  get "library_detail", to: "libraries#show", as: "library_detail"

  resources :library_settings, only: [ :index, :create, :destroy ] do
  end


  get 'libraries/nearby', to: 'libraries#nearby'


  resources :want_to_read_books, only: [:index, :create, :destroy], param: :isbn
  resources :already_read_books, only: [:index, :create, :destroy], param: :isbn
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :user_libraries, dependent: :destroy
  has_many :users, through: :user_libraries

    def self.ransackable_attributes(auth_object = nil)
      [ "formal", "address", "libkey" ]
    end

    def self.ransackable_associations(auth_object = nil)
      [ "user_libraries", "users" ]
    end

    scope :search, ->(query) { where("formal LIKE ? OR address LIKE ?", "%#{query}%", "%#{query}%") }

    def latitude
      geocode.split(',')[1].to_f
    end
  
    def longitude
      geocode.split(',')[0].to_f
    end

end

app/controllers/libraries_controller.rb
require "net/http"
require "json"

class LibrariesController < ApplicationController
  def show
    @library = Library.find_by(geocode: params[:geocode])
    @pref = extract_prefecture(@library.address)

    Rails.logger.debug("取得したパラメータ (geocode): #{@geocode}")
    Rails.logger.debug("表示するデータ: #{@library}")

    if @library.nil?
      flash.now[:alert] = "図書館情報が見つかりませんでした。geocode: #{@geocode}"
    end
  end

  def fetch_and_save_libraries
    endpoint = "https://api.calil.jp/library"
    params = {
    appkey: ENV["CALIL_API_KEY"],
    format: "json",
    limit: "100"
  }

  uri = URI(endpoint)
  uri.query = URI.encode_www_form(params)

  response = Net::HTTP.get_response(uri)
  response_body_utf8 = response.body.force_encoding("UTF-8")

  if response_body_utf8.start_with?("callback(") && response_body_utf8.end_with?(");")
    rjson = response_body_utf8.delete_prefix("callback(").delete_suffix(");")
  else
    rjson = response_body_utf8
  end

  begin
    libraries_data = JSON.parse(rjson)
    libraries_data.each do |library|
      Library.find_or_create_by(libkey: library["libkey"]) do |lib|
        lib.address = library["address"]
        lib.tel = library["tel"]
        lib.post = library["post"]
        lib.formal = library["formal"]
        lib.url_pc = library["url_pc"]
        lib.geocode = library["geocode"]
      end
    end
  rescue JSON::ParserError => e
    Rails.logger.error("JSONの解析エラー: #{e.message}")
  end
end

private

  PREFECTURES = %w[
    北海道 青森県 岩手県 宮城県 秋田県 山形県 福島県
    茨城県 栃木県 群馬県 埼玉県 千葉県 東京都 神奈川県
    新潟県 富山県 石川県 福井県 山梨県 長野県 岐阜県
    静岡県 愛知県 三重県 滋賀県 京都府 大阪府 兵庫県 奈良県 和歌山県
    鳥取県 島根県 岡山県 広島県 山口県 徳島県 香川県 愛媛県 高知県
    福岡県 佐賀県 長崎県 熊本県 大分県 宮崎県 鹿児島県 沖縄県
  ].freeze

  def extract_prefecture(address)
    PREFECTURES.detect { |pref| address.include?(pref) } || "不明"
  end

  def build_regions_data
    regions_data = {}
    # データベースから地域情報を取得
    Library.select(:region).distinct.each do |lib|
      regions_data[lib.region] ||= []
      regions_data[lib.region] << lib.prefecture
    end
    regions_data
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/show.html.erb
<div class="container mx-auto p-6">
  <h1 class="text-2xl font-bold mb-6 text-gray-800">図書館詳細情報</h1>

  <% if flash[:alert] %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">エラー！</strong>
      <span class="block sm:inline"><%= flash[:alert] %></span>
    </div>
  <% elsif @library %>
    <div class="bg-white shadow-md rounded-lg overflow-hidden">
      <div class="px-6 py-4 bg-gray-100 border-b border-gray-200">
        <h2 class="text-xl font-semibold text-gray-700"><%= @library.formal %></h2>
      </div>

      <div class="p-6">
        <h3 class="font-semibold text-lg text-gray-700 mb-3">連絡先</h3>
        <div class="mb-4">
          <div class="grid grid-cols-3 gap-4 mb-2">
            <div class="font-medium text-gray-600">住所</div>
            <div class="col-span-2 text-gray-700"><%= @library.address %></div>
          </div>
          <div class="grid grid-cols-3 gap-4 mb-2">
            <div class="font-medium text-gray-600">電話番号</div>
            <div class="col-span-2 text-gray-700"><%= @library.tel %></div>
          </div>
          <div class="grid grid-cols-3 gap-4 mb-2">
            <div class="font-medium text-gray-600">郵便番号</div>
            <div class="col-span-2 text-gray-700"><%= @library.post %></div>
          </div>
        </div>

        <h3 class="font-semibold text-lg text-gray-700 mb-3 mt-5">図書館情報</h3>
        <div>
          <div class="grid grid-cols-3 gap-4 mb-2">
            <div class="font-medium text-gray-600">図書館キー</div>
            <div class="col-span-2 text-gray-700"><%= @library.libkey %></div>
          </div>
          <div class="grid grid-cols-3 gap-4 mb-2">
            <div class="font-medium text-gray-600">正式名称</div>
            <div class="col-span-2 text-gray-700"><%= @library.formal %></div>
          </div>
          <div class="grid grid-cols-3 gap-4 mb-2">
            <div class="font-medium text-gray-600">緯度経度</div>
            <div class="col-span-2 text-gray-700"><%= @library.geocode %></div>
          </div>
        </div>

        <div class="grid grid-cols-3 gap-4 mb-2">
          <div class="font-medium text-gray-600">予約</div>
          <div class="col-span-2 text-gray-700">
            <% if @library.url_pc.present? %>
              <%= link_to "本を予約する", @library.url_pc, target: '_blank', class: "inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
            <% else %>
              <span class="text-gray-500">予約URLがありません</span>
            <% end %>
          </div>
        </div>
      </div>
      <div id="mapid" style="height: 400px; margin: 32px; border: solid; border-color: #c0c0c0; border-width: 1px; box-shadow: 2px 2px 2px #c0c0c0;"></div> <!-- 高さを設定 -->
<!-- Googleマップ表示用の Javascript -->
<script>
  var map = L.map('mapid').setView([<%= @library.latitude %>,<%= @library.longitude %>], 15);
  var osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {


  });
  var gsi = L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png', {
    attribution: "<a href='https://maps.gsi.go.jp/development/ichiran.html' target='_blank'>地理院タイル</a>"
  });


  var baseMaps = {
    "OpenStreetMap" : osm,
    "国土地理院地図" : gsi
  };
  L.control.layers(baseMaps).addTo(map);
  osm.addTo(map);

  //JIG-SAW本社の位置にマーカーを追加する。
  var marker = L.marker([<%= @library.latitude %>,<%= @library.longitude %>]).addTo(map);
  //上のマーカーにポップアップを追加する。
  marker.bindPopup("【<%= @library.formal %>】</br><%= @library.geocode %>").openPopup();

</script>



      <div class="px-6 py-4 bg-gray-100 border-t border-gray-200">
        <%= link_to "都道府県別一覧に戻る", region_path(pref_name: @pref), class: "inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
      </div>
    </div>
  <% else %>
    <div class="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4" role="alert">
      <p>図書館情報を取得できませんでした。</p>
    </div>
  <% end %>
</div>